$(function(){
  $('#companies').tokenInput([
      {name: "Abbott Group:CC2382"},
      {name: "Abbott, Kunze and Simonis:CC2480"},
      {name: "Abbott, Roberts and Mann:CC7891"},
      {name: "Abernathy Group:CC7854"},
      {name: "Abshire Inc:CC0554"},
      {name: "Abshire, Lindgren and Beier:CC8253"},
      {name: "Adams LLC:CC1357"},
      {name: "Altenwerth Inc:CC1466"},
      {name: "Anderson Group:CC6078"},
      {name: "Ankunding-Dach:CC0082"},
      {name: "Ankunding-Streich:CC0014"},
      {name: "Armstrong, Tromp and Kemmer:CC6614"},
      {name: "Armstrong-Spinka:CC4713"},
      {name: "Auer, Kerluke and Casper:CC8877"},
      {name: "Aufderhar LLC:CC9097"},
      {name: "Bahringer PLC:CC9485"},
      {name: "Bahringer-Bruen:CC5234"},
      {name: "Bailey, Gerlach and Blanda:CC4942"},
      {name: "Bailey-Legros:CC9920"},
      {name: "Bailey-Nikolaus:CC4680"},
      {name: "Balistreri Ltd:CC7669"},
      {name: "Barrows PLC:CC4146"},
      {name: "Barrows, Bruen and Wisozk:CC2317"},
      {name: "Bartell and Sons:CC2070"},
      {name: "Bartell-Brakus:CC3532"},
      {name: "Bartell-Stracke:CC2454"},
      {name: "Bartell-Streich:CC4367"},
      {name: "Bartoletti Group:CC8713"},
	  {name: "Bartoletti-Hahn:CC4054"},
	  {name: "Bartoletti-Spinka:CC3553"},
	  {name: "Bashirian, McLaughlin and Medhurst:CC0273"},
	  {name: "Bashirian-West:CC7756"},
	  {name: "Batz Inc:CC6844"},
	  {name: "Batz Ltd:CC7664"},
	  {name: "Batz PLC:CC0117"},
	  {name: "Bauch LLC:CC8679"},
	  {name: "Bauch-Macejkovic:CC3807"},
	  {name: "Baumbach Ltd:CC5791"},
	  {name: "Baumbach-Purdy:CC7678"},
	  {name: "Bayer Ltd:CC1524"},
	  {name: "Beahan, Little and Howe:CC4073"},
	  {name: "Beahan-Wyman:CC7410"},
	  {name: "Beatty Inc:CC0712"},
	  {name: "Beatty, Legros and Weissnat:CC3640"},
	  {name: "Bechtelar, Grady and Beier:CC9537"},
	  {name: "Becker Inc:CC9722"},
	  {name: "Bednar and Sons:CC1089"},
	  {name: "Bednar Ltd:CC7930"},
	  {name: "Bednar, Fisher and Sanford:CC0277"},
	  {name: "Bednar-Doyle:CC0557"},
	  {name: "Beer PLC:CC3079"},
	  {name: "Beier Group:CC8938"},
	  {name: "Berge, Tillman and McClure:CC6578"},
	  {name: "Berge-Grimes:CC4448"},
	  {name: "Berge-Haley:CC2509"},
	  {name: "Berge-Senger:CC4982"},
	  {name: "Bergstrom-Glover:CC2838"},
	  {name: "Bernhard, Nitzsche and Gutmann:CC4312"},
	  {name: "Bernier and Sons:CC8555"},
	  {name: "Bernier, Hegmann and Corwin:CC0767"},
	  {name: "Bernier-Adams:CC9761"},
	  {name: "Bins-Mitchell:CC3724"},
	  {name: "Blanda, Ziemann and Tremblay:CC9885"},
	  {name: "Blanda-Mayert:CC6948"},
	  {name: "Blanda-Streich:CC8943"},
	  {name: "Blick, Rosenbaum and Kunze:CC7255"},
	  {name: "Block and Sons:CC1483"},
	  {name: "Block Group:CC3272"},
	  {name: "Block LLC:CC8591"},
	  {name: "Block-Orn:CC9076"},
	  {name: "Bode Group:CC6489"},
	  {name: "Bode Inc:CC9941"},
	  {name: "Bode, Lehner and Schroeder:CC0028"},
	  {name: "Bode, Reinger and Gaylord:CC2893"},
	  {name: "Bode-Johnston:CC8965"},
	  {name: "Boehm LLC:CC9649"},
	  {name: "Boehm, Huels and Auer:CC2589"},
	  {name: "Bogan Group:CC5154"},
	  {name: "Bogan Ltd:CC1275"},
	  {name: "Bogan, Leuschke and Boyer:CC5076"},
	  {name: "Bogan-Predovic:CC7406"},
	  {name: "Bogisich LLC:CC4523"},
	  {name: "Bogisich, Koepp and Cartwright:CC9913"},
	  {name: "Borer, Armstrong and Mitchell:CC5501"},
	  {name: "Bosco, Kunze and Graham:CC8272"},
	  {name: "Bosco, Schultz and Adams:CC5829"},
	  {name: "Botsford, Howe and Ward:CC9058"},
	  {name: "Botsford-Mayer:CC3530"},
	  {name: "Boyer LLC:CC6398"},
	  {name: "Boyer Ltd:CC9543"},
	  {name: "Boyle, Jakubowski and Blanda:CC7714"},
	  {name: "Boyle, Schumm and Rath:CC6459"},
	  {name: "Bradtke LLC:CC8601"},
	  {name: "Bradtke Ltd:CC5934"},
	  {name: "Bradtke, Torp and Schmitt:CC8878"},
	  {name: "Bradtke-Stanton:CC9870"},	  
    ], {    
      hintText: "Company Code or Name",
      noResultsText: "No result found ",
      searchingText: "searching...",
      preventDuplicates: true
  }); 

});